---
title: "Clean Data (Resturants, Bars and Clubs)"
output: html_notebook
---
# Resturant
```{r}
library(openxlsx)
library(xlsx)

dat <- read.xlsx("../data/DOHMH_New_York_City_Restaurant_Inspection_Results.xlsx",1)
str(dat)
```

## Manhattan Only
```{r}
library(dplyr)

res.mah <- dat %>%
  distinct(BUILDING, STREET, ZIPCODE,.keep_all = TRUE) %>%
  filter(BORO == "MANHATTAN")
write.csv(res.mah, file = "../output/Resturant/Resturant_Mah.csv")
```

## Put in geo loc
```{r}
library(dplyr)
library(ggmap)

res.mah <- read.csv("../output/Resturant/Resturant_Mah.csv")
res.mah.short <- res.mah %>%
  select(DBA, BUILDING, STREET, ZIPCODE, CUISINE.DESCRIPTION)


# res.mah1 <- res.mah[1:2400, ]
# loc1 <- res.mah1 %>%
#   select("DBA", "BUILDING", "STREET", "ZIPCODE", "PHONE", "CUISINE.DESCRIPTION", "GRADE")%>%
#   mutate(ADDRESS = paste(BUILDING, STREET, "New York, NY", sep = ", ")) %>%
#   mutate_geocode(ADDRESS)
# write.csv(loc1, file = "../output/Resturant/resturant_location00.csv")
```

```{r}
for (i in 0:3){
  if((i+1)*2400 < nrow(res.mah.short)){
  n = i*2400+1
  data = res.mah.short[n:(n+2400-1), ]
  }
  else{
    data = res.mah.short[(i*2400+1):nrow(res.mah.short), ]
  }
  path <- paste0("../output/Resturant/resturant_location", i, ".csv")
  write.csv(data, file = path)
}
# 
# write.csv(test, file = path)
```

```{r}

```


# Bars and Clubs
```{r}
dat2 <- read.csv("../data/Liquor_Authority_Quarterly_List_of_Active_Licenses.csv", 
                 header = TRUE, na.strings = "NA", as.is = TRUE)
str(dat2)
lapply(dat2, class)
```

```{r}
count.mah <- dat2 %>%
  distinct(License.Serial.Number, .keep_all = TRUE) %>%
  group_by(County.Name..Licensee.) %>%
  summarise(value = n())

liquor.ny <- dat2 %>%
  distinct(License.Serial.Number, .keep_all = TRUE) %>%
  filter(County.Name..Licensee. == "NEW YORK")

count.type <- liquor.ny %>%
  group_by(License.Type.Name) %>%
  summarise(value = n())

wine <- liquor.ny %>%
  filter(License.Type.Name == "TAVERN WINE")
write.csv(wine, file = "../output/Resturant/wine.csv")

bars <- liquor.ny %>%
  filter(License.Type.Name == "ON-PREMISES LIQUOR")
write.csv(bars, file = "../output/Resturant/bars.csv")

clubs <- liquor.ny %>%
  filter(License.Type.Name == "CLUB LIQUOR" | License.Type.Name == "CLUB WINE")
write.csv(clubs, file = "../output/Resturant/clubs.csv")
```

# New Resturant Data
```{r}
library(dplyr)
dat <- read.csv("../data/Resturant.csv")
zipcode <- c(seq(10001, 10007), seq(10009, 10014), seq(10016, 10019), seq(10021, 10040), 
             "10065", "10069", "10075", "10128", "10280", "10282", "11106", "11109", "11231")
dat <- dat %>%
  filter(is.na(lon) == FALSE, is.na(lat) == FALSE, ZIPCODE %in% zipcode)

count.zip <- dat %>%
  group_by(ZIPCODE) %>%
  summarise(COUNT = n()) %>%
  mutate(RANKING = rank(desc(COUNT)))

write.csv(dat, file = "../data/Res_fil.csv")
write.csv(count.zip, file = "../data/Res_count.csv")
```

# Bar/ Clubs
```{r}
bars <- read.csv("../output/Resturant/bars.csv")
clubs <- read.csv("../output/Resturant/clubs.csv")
wine <- read.csv("../output/Resturant/wine.csv")
str(bars)

bars <- bars %>%
  select(Premises.Name, Doing.Business.As..DBA., Actual.Address.of.Premises..Address1.,
         Additional.Address.Information..Address2., 
         City, State, Zip, Latitude, Longitude, Location) %>%
  filter(is.na(Location) == FALSE, Zip %in% zipcode)

wine <- wine %>%
  select(Premises.Name, Doing.Business.As..DBA., Actual.Address.of.Premises..Address1.,
         Additional.Address.Information..Address2., 
         City, State, Zip, Latitude, Longitude, Location) %>%
  filter(is.na(Location) == FALSE, Zip %in% zipcode)

clubs <- clubs %>%
  select(Premises.Name, Doing.Business.As..DBA., Actual.Address.of.Premises..Address1.,
         Additional.Address.Information..Address2., 
         City, State, Zip, Latitude, Longitude, Location) %>%
  filter(is.na(Location) == FALSE, Zip %in% zipcode)

write.csv(bars, file = "../data/Bars.csv")
write.csv(clubs, file = "../data/Clubs.csv")
write.csv(wine, file = "../data/Wine.csv")
```

```{r}
count.bars <- bars %>%
  group_by(Zip) %>%
  summarise(COUNT = n()) %>%
  mutate(RANKING = rank(desc(COUNT)))

count.wine <- wine %>%
  group_by(Zip) %>%
  summarise(COUNT = n()) %>%
  mutate(RANKING = rank(desc(COUNT)))

count.clubs <- clubs %>%
  group_by(Zip) %>%
  summarise(COUNT = n()) %>%
  mutate(RANKING = rank(desc(COUNT)))

write.csv(count.bars, file = "../data/bars_count.csv")
write.csv(count.wine, file = "../data/wine_count.csv")
write.csv(count.clubs, file = "../data/clubs_count.csv")
```

